### ISSUE TITLE
unicode problem

### ISSUE THREAD

**Issue by vrabaud** [matiasb/python-unidiff#12]
Hi, I just repeated your tutorial with the latest from pip and it fails with the following URL (that diff has a unicode character):

    import urllib2
    from unidiff import PatchSet
    diff = urllib2.urlopen('https://github.com/ros/rosdistro/pull/6619.diff')
    patch = PatchSet(diff)

/usr/local/lib/python2.7/dist-packages/unidiff/patch.pyc in __str__(self)
     75 
     76     def __str__(self):
---> 77         return "%s%s" % (self.line_type, self.value)
     78 
     79     @property

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)

Thx

**Comment by matiasb** [comment]
Fixed in 494b8846420c6879aaa8b47402ed71df3150e8e7 (released along a few more changes in v0.5.1), added optional encoding parameter to PatchSet initialization (README example updated).
