### ISSUE TITLE
New release including performance improvements?

### ISSUE THREAD

**Issue by guykisel** [matiasb/python-unidiff#20]
Hi, Unidiff is great! I'm using it in https://github.com/guykisel/inline-plz and it makes my life much easier.

In https://github.com/matiasb/python-unidiff/pull/16 there were some nice performance optimizations, but the release on PyPI doesn't appear to include them. I would be very grateful if you could put up a new release of your package including the improvements.

**Comment by messense** [comment]
+1

**Comment by matiasb** [comment]
Thanks :-)
I was planning to work on some other updates before a new release, but given that it seems I can't find the time, let me prepare a minor release to PyPI for this week.

**Comment by matiasb** [comment]
v0.5.2 released!
Sorry for not tackling this before.

**Comment by guykisel** [comment]
@matiasb thank you! :)
