### ISSUE TITLE
Add patch position

### ISSUE THREAD

**Issue by grantmcconnaughey** [matiasb/python-unidiff#37]
Hello! I have a feature request for you: adding patch position to a line.

"Patch position" is, admittedly, not an official diff term. But it's something [GitHub uses in their API when making PR comments](https://developer.github.com/v3/pulls/comments/#input). Users aren't actually commenting on a line by its line number in GitHub. Instead, their really commenting on the position of the line in a diff.

**Comment by matiasb** [comment]
Reviewing, isn't diff_line_no what you want? If it is not, please feel free to reopen and tell me more :-)
It was introduced in b10f7af6e717bb5d0c37c5200b1fe0b6bf94ca44 (released in 0.5.2).
(and also, sorry for the delay in the response)
