### ISSUE TITLE
0.5.2 missing from PyPi

### ISSUE THREAD

**Issue by mr337** [matiasb/python-unidiff#57]
Hi,

Having issues installed unidiff 0.5.2 from pypi. It is shown as a release https://pypi.org/project/unidiff/0.5.2/, but no files associated with it thus pip can't install. 

https://pypi.org/simple/unidiff/

Thanks!

**Comment by matiasb** [comment]
Hi,

Hm.. I see. If I remember correctly, I released 0.5.2 as 0.5.3 to PyPI because I had some issues with the upload, and then I couldn't re-upload it. I should probably try to remove 0.5.2 from PyPI.

Were you looking for 0.5.2 for something in particular?
Thanks for your report!

**Comment by mr337** [comment]
Not really, just a version we use in our application. Looking to get it updated sooner than later ;D

**Comment by matiasb** [comment]
Ok, I just built the wheel package for 0.5.2 and uploaded it to PyPI to make sure there is a downloadable version for that release. From a quick look, I think I may be able to upload a post-release src package if needed.

**Comment by mr337** [comment]
Thank you!
