### ISSUE TITLE
Test fails for autocrlf config

### ISSUE THREAD

**Issue by CirQ** [matiasb/python-unidiff#64]
I've cloned the latest code to my machine and run the test suite by `python setup.py test`. Then I encountered 5 failures:

```bash
======================================================================
FAIL: test_encoding_param (tests.test_parser.TestUnidiffParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\cirq\desktop\python-unidiff\tests\test_parser.py", line 69, in test_encoding_param
    self.assertEqual(added_unicode_line.value, 'holá mundo!\n')
AssertionError: 'holá mundo!\r\n' != 'holá mundo!\n'
- holá mundo!
?            -
+ holá mundo!


======================================================================
FAIL: test_no_newline_at_end_of_file (tests.test_parser.TestUnidiffParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\cirq\desktop\python-unidiff\tests\test_parser.py", line 83, in test_no_newline_at_end_of_file
    self.assertEqual(added_unicode_line.value, ' No newline at end of file\n')
AssertionError: ' No newline at end of file\r\n' != ' No newline at end of file\n'
-  No newline at end of file
?                           -
+  No newline at end of file


======================================================================
FAIL: test_parse_sample (tests.test_parser.TestUnidiffParser)
Parse sample file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\cirq\desktop\python-unidiff\tests\test_parser.py", line 135, in test_parse_sample
    self.assertEqual(res[0][0].section_header, 'Section Header')
AssertionError: 'Section Header\r' != 'Section Header'
?               -
+ Section Header

======================================================================
FAIL: test_print_hunks_without_gaps (tests.test_parser.TestUnidiffParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\cirq\desktop\python-unidiff\tests\test_parser.py", line 114, in test_print_hunks_without_gaps
    self.assertEqual(lines[12], '@@ -5,16 +11,10 @@')
AssertionError: '@@ -5,16 +11,10 @@ ' != '@@ -5,16 +11,10 @@'
- @@ -5,16 +11,10 @@
?                   -
+ @@ -5,16 +11,10 @@


======================================================================
FAIL: test_samples (tests.test_parser.TestVCSSamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\cirq\desktop\python-unidiff\tests\test_parser.py", line 329, in test_samples
    self.assertEqual(diff_file.read(), str(res))
AssertionError: "=== [127 chars],4 @@\r\n+This was missing!\r\n+Adding it now.[666 chars]\r\n" != "=== [127 chars],4 @@ \r\n+This was missing!\r\n+Adding it now[655 chars]le\n"
Diff is 1139 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 32 tests in 0.021s

FAILED (failures=5)
Test failed: <unittest.runner.TextTestResult run=32 errors=0 failures=5>
error: Test failed: <unittest.runner.TextTestResult run=32 errors=0 failures=5>
```

It seems that my git local config has the option `core.autocrlf` to be `True`, hence the test samples are appended with CRLF line ending (i.e., `\r\n`). This auto line ending fixing breaks the assertion.

Is this a bug of the library?

**Comment by matiasb** [comment]
The library (and more specifically, the tests) does not use or depend on git in any way, so git settings shouldn't have effects here. On the other hand, tests use files already included in the project, so it seems something more related to how the file is read by Python when opening it in the test.

What Python version are you using? Which operating system?

Thanks.

**Comment by CirQ** [comment]
> 
> 
> The library (and more specifically, the tests) does not use or depend on git in any way, so git settings shouldn't have effects here. On the other hand, tests use files already included in the project, so it seems something more related to how the file is read by Python when opening it in the test.
> 
> What Python version are you using? Which operating system?
> 
> Thanks.

This failure can be reproduced by:
```bash
$ git config --global core.autocrlf true
$ git clone https://github.com/matiasb/python-unidiff
$ cd python-unidiff
$ python3 setup.py test
```
On an Ubuntu 18.04 system, by the bundled Python 3.6.9.

However, I found that this test fail is because I misuse the `core.autocrlf` option, for which all text files  are appended with `\r\n` line ending, no matter what the original line endings are.

Another consideration is that can we ignore the line endings? Since most diffs are line-based, and the endings are not essential in most cases (just my opinion). I noticed that there is a test method `test_preserve_dos_line_endings` in `test_parser.py`, which concerns the line ending issue. Does it necessary to do so?

**Comment by matiasb** [comment]
Ok, I see, makes sense (re how the issue is reproduced).

Hmm.. not sure what you mean by ignoring line endings. I think being able to detect a different line ending in a diff helps identifying possible issues (e.g. some config files).

The idea of the test is to confirm that the library is not altering the line endings from the original diff data.

**Comment by CirQ** [comment]
I got the point, and that's why I blame this test fail to I misuse the `git config`. Thx bro : )
