### ISSUE TITLE
Issue parsing files with space in filename

### ISSUE THREAD

**Issue by dperecab** [matiasb/python-unidiff#93]
Whenever there is a space in the route of the file, I keep getting the following error:

`File "/usr/local/lib/python3.9/site-packages/unidiff/patch.py", line 460, in __init__
    self._parse(data, encoding=encoding, metadata_only=metadata_only)
  File "/usr/local/lib/python3.9/site-packages/unidiff/patch.py", line 530, in _parse
    raise UnidiffParseError('Target without source: %s' % line)
unidiff.errors.UnidiffParseError: Target without source: +++ b/Audit Repositories/Interfaces/IMaintTransactionRepository.cs`

This is an example:
`diff --git a/Audit Repositories/Interfaces/IMaintTransactionRepository.cs b/Audit Repositories/Interfaces/IMaintTransactionRepository.cs
new file mode 100644
index 0000000..f95add3`

or another one:
`diff --git a/repairer_allocation_etl/src/test/resources/NCR API GW.postman_collection.json b/repairer_allocation_etl/src/test/resources/NCR API GW.postman_collection.json
new file mode 100644
index 0000000..fdd8387`

While debugging, I've seen that current_file.target_file is set to "Repositories/Interfaces/IMaintTransactionRepository.cs", while target_file is being correctly set to "b/Audit Repositories/Interfaces/IMaintTransactionRepository.cs"

**Comment by krobelus** [comment]
On Mon, Feb 21, 2022 at 01:20:35AM -0800, dperecab wrote:
> Whenever there is a space in the route of the file, I keep getting the following error:

Probably we need to strip a trailing tab character, see commit
1a9eb3b9d5 (git-diff/git-apply: make diff output a bit friendlier to GNU patch (part 2), 2006-09-22)
in git/git

**Comment by matiasb** [comment]
To confirm, was this related to a trailing tab character as mentioned? That would probably break the parsing regex, but I guess there shouldn't be a tab there? If you are still having issues, let me know, and if possible share some specific example and/or how you generate the diff. Thanks!

**Comment by dperecab** [comment]
It is the space character in the path of the file what is causing the issue. 
There is an if in row 529 of patch.py with this condition: current_file.target_file == target_file
When there is a space character in the path of the file, this validation does not match, causing the error

**Comment by DevArcana** [comment]
Changing the regex to the following seems to fix this type of error:

```python
RE_DIFF_GIT_HEADER = re.compile(
    r'^diff --git (?P<source>a/.+) (?P<target>b/.+)')
```

Can anyone shed some light on whether that is going to break anything?
